/* code automatically generated by bin2c -- DO NOT EDIT */
{
/* #include'ing this file in a C program is equivalent to calling
  if (luaL_loadfile(L,"luac.out")==0) lua_pcall(L, 0, 0, 0); 
*/
/* luac.out */
static const unsigned char B1[]={
 27, 76,117, 97, 81,  0,  1,  4,  8,  4,  8,  0, 11,  0,  0,  0,  0,  0,  0,  0,
 64,104,101,108,108,111, 46,108,117, 97,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  2,  2,  5,  0,  0,  0,  5,  0,  0,  0, 65, 64,  0,  0, 29,  0,  0,  1, 30,
  0,  0,  0, 30,  0,128,  0,  2,  0,  0,  0,  4,  6,  0,  0,  0,  0,  0,  0,  0,
112,114,105,110,116,  0,  4, 14,  0,  0,  0,  0,  0,  0,  0, 72,101,108,108,111,
 44, 32,119,111,114,108,100, 33,  0,  0,  0,  0,  0,  5,  0,  0,  0,  1,  0,  0,
  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,
};

 if (luaL_loadbuffer(L,(const char*)B1,sizeof(B1),"luac.out")==0) lua_pcall(L, 0, 0, 0);
}
